services:
  backend:
    build: ./backend
    container_name: p2p-backend
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    container_name: p2p-frontend
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    container_name: p2p-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    command: /bin/bash -c "rm -f /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - frontend
      - backend

